### ISSUE TITLE
Unhandled exception in Windows 10 chinese

### ISSUE THREAD

**Issue by xmlspyspring** [ecki/net-tools#29]
I ran the following code and got the following error:

code:
```dart
import 'package:network_tools/network_tools.dart';

import '../example_utils.dart';

Future<void> main() async {
  enableExampleLogging();
  await configureNetworkTools('build');

  const String subnet = '192.168.1'; //Default network id for home networks

  // final interface = await NetInterface.localInterface();
  // final netId = interface?.networkId;
  // if (netId != null) {
  //   subnet = netId;
  // }

  // or You can also get address using network_info_plus package
  // final String? address = await (NetworkInfo().getWifiIP());
  examplesLogger.fine("Starting scan on subnet $subnet");

  // You can set [firstHostId] and scan will start from this host in the network.
  // Similarly set [lastHostId] and scan will end at this host in the network.
  final stream = HostScannerService.instance.getAllPingableDevicesAsync(
    subnet,
    // firstHostId: 1,
    // lastHostId: 254,
    progressCallback: (progress) {
      examplesLogger.finer('Progress for host discovery : $progress');
    },
  );

  stream.listen(
    (host) async {
      //Same host can be emitted multiple times
      //Use Set<ActiveHost> instead of List<ActiveHost>
      examplesLogger.fine('Found device: ${await host.toStringFull()}');
    },
    onDone: () {
      examplesLogger.fine('Scan completed');
    },
  ); // Don't forget to cancel the stream when not in use.
}
``` 

console output:
```powershell
C:/a_dev/flutter-sdk/bin/cache/dart-sdk/bin/dart.exe --enable-asserts C:\Users\xmlspyspring\IdeaProjects\look_net_cli\bin\look_net_cli.dart
Positional arguments: []
2024-03-25 15:29:02.881110: FINE: network_tools: Downloading mac-vendors-export.csv from network_tools
Unhandled exception:
ClientException with SocketException: Failed host lookup: 'raw.githubusercontent.com' (OS Error: 请求的名称有效，但是找不到请求的类型的数据。
, errno = 11004), uri=https://raw.githubusercontent.com/osociety/network_tools/main/lib/assets/mac-vendors-export.csv
#0      IOClient.send (package:http/src/io_client.dart:154:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      _withClient (package:http/http.dart:167:12)
<asynchronous suspension>
#3      VendorTable._fetchVendorTable (package:network_tools/src/device_info/vendor_table.dart:42:24)
<asynchronous suspension>
#4      VendorTable.createVendorTableMap (package:network_tools/src/device_info/vendor_table.dart:31:25)
<asynchronous suspension>
#5      configureNetworkTools (package:network_tools/src/configure_dart_native.dart:37:3)
<asynchronous suspension>
#6      main (file:///C:/Users/xmlspyspring/IdeaProjects/look_net_cli/bin/look_net_cli.dart:87:3)
<asynchronous suspension>

Process finished with exit code 255
``` 

My Environment:   windows 10 chinese
```powershell
PS C:\Users\xmlspyspring\IdeaProjects\network_tools> dart --version
Dart SDK version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "windows_x64"
```
I have solved this problem:
In  file  lib/src/services/impls/host_scanner_service_impl.dart Line 110 
change 
`Ping(host, count: 1, timeout: timeoutInSeconds)`
to
`Ping(host, count: 1, timeout: timeoutInSeconds,forceCodepage: true`

then run and get:
````
C:/a_dev/flutter-sdk/bin/cache/dart-sdk/bin/dart.exe --enable-asserts C:\Users\xmlspyspring\IdeaProjects\network_tools\example\lib\scan\host_scan.dart
2024-03-25 18:22:47.681016: FINE: network_tools_examples: Starting scan on subnet 192.168.1
2024-03-25 18:22:54.382557: FINE: network_tools_examples: Found device: Address: 192.168.1.1, MAC: null, HostId: 1, Vendor: null Time: 1ms, DeviceName: Generic Device, HostName: null, MdnsInfo: null
2024-03-25 18:22:58.921379: FINE: network_tools_examples: Found device: Address: 192.168.1.2, MAC: null, HostId: 2, Vendor: null Time: 46ms, DeviceName: Generic Device, HostName: null, MdnsInfo: null
2024-03-25 18:23:03.459363: FINE: network_tools_examples: Found device: Address: 192.168.1.4, MAC: null, HostId: 4, Vendor: null Time: 229ms, DeviceName: Generic Device, HostName: null, MdnsInfo: null
2024-03-25 18:23:03.469368: FINE: network_tools_examples: Found device: Address: 192.168.1.5, MAC: null, HostId: 5, Vendor: null Time: 1ms, DeviceName: host.docker.internal, HostName: host.docker.internal, MdnsInfo: null
2024-03-25 18:23:19.845421: FINE: network_tools_examples: Scan completed
````
Too little information obtained, many are null. I want to get more information, especially the mac address.

**Comment by ecki** [comment]
This is not dart network tools project.
